title:            Monish Appusamy
description:      A personal portfolio site of Monish Kumar Appusamy
url:              # monish.co.in
signoff:          # Monish Kumar Appusamy.
disqus_shortname: # Monish
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         LinkedIn
    url:          http://linkedin.com/in/monishappusamy
    external:     true
  - name:         GitHub
    url:          http://github.com/monishappusamy
    external:     true
  - name:         Hackerrank
    url:          https://www.hackerrank.com/monishappusamy
    external:     true
  - name:         Projects
    url:          /projects
  - name:         Blog
    url:          http://monishappusamy.blogspot.com
    external:     true
  - name:         Email
    url:          mailto:monishappusamy@gmail.com
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
